# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'euskoevents' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for euskoevents
	pod 'Eureka', '~> 4.0'
	pod 'Alamofire', '~> 4.6'
	pod 'SwiftyJSON', '~> 4.0'
end
